services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    develop:
      watch:
        - action: sync+restart
          path: ./nginx/conf.d
          target: /etc/nginx/conf.d
        - action: sync+restart
          path: ./nginx/nginx.conf
          target: /etc/nginx/nginx.conf
        - action: sync+restart
          path: ./nginx/njs
          target: /etc/nginx/njs

